steps:
  - label: ":docker: Local Build (Small)"
    key: "local-build-small"
    command: |
      docker context ls
      docker buildx ls
      docker buildx build --builder default -t docker-benchmark:local-small .
    agents:
      queue: "linux-small"

  - label: ":docker: Local Build (Medium)"
    key: "local-build-medium"
    command: |
      docker context ls
      docker buildx ls
      docker buildx build --builder default -t docker-benchmark:local-medium .
    agents:
      queue: "linux-medium"

  - label: ":docker: Local Build (Large)"
    key: "local-build-large"
    command: |
      docker context ls
      docker buildx ls
      docker buildx build --builder default -t docker-benchmark:local-large .
    agents:
      queue: "linux-large"

  - label: ":cloud: Remote Build (Small)"
    key: "remote-build-small"
    command: |
      docker context ls
      docker buildx ls
      docker buildx build -t docker-benchmark:remote-small .
    agents:
      queue: "linux-small"

  - label: ":cloud: Remote Build (Medium)"
    key: "remote-build-medium"
    command: |
      docker context ls
      docker buildx ls
      docker buildx build -t docker-benchmark:remote-medium .
    agents:
      queue: "linux-medium"

  - label: ":cloud: Remote Build (Large)"
    key: "remote-build-large"
    command: |
      docker context ls
      docker buildx ls
      docker buildx build -t docker-benchmark:remote-large .
    agents:
      queue: "linux-large"
