steps:
  - group: ":cloud: Remote Builds"
    steps:
      - label: "Large Agent"
        key: "remote-build-large"
        command: docker buildx build --progress=plain -t docker-benchmark:remote-large .
        agents:
          queue: "linux-large"

      - wait

      - label: "Medium Agent"
        key: "remote-build-medium"
        command: docker buildx build --progress=plain -t docker-benchmark:remote-medium .
        agents:
          queue: "linux-medium"

      - wait

      - label: "Small Agent"
        key: "remote-build-small"
        command: docker buildx build --progress=plain -t docker-benchmark:remote-small .
        agents:
          queue: "linux-small"

  - wait

  - group: ":docker: Local Builds"
    steps:
      - label: "Large Agent"
        key: "local-build-large"
        command: docker buildx build --builder default --progress=plain -t docker-benchmark:local-large .
        agents:
          queue: "linux-large"

      - wait

      - label: "Medium Agent"
        key: "local-build-medium"
        command: docker buildx build --builder default --progress=plain -t docker-benchmark:local-medium .
        agents:
          queue: "linux-medium"

      - wait

      - label: "Small Agent"
        key: "local-build-small"
        command: docker buildx build --builder default --progress=plain -t docker-benchmark:local-small .
        agents:
          queue: "linux-small"
